
/*
 *    This program is free software; you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation; either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with this program; if not, write to the Free Software
 *    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 *
 *
 *    I would like to express my appreciation to Dr. Yasser EL-Manzalawy
 *    for his open source project Epitopes Toolkit
 *    that i used in EMAS under the terms of the GNU General Public License.
 *      Copyright (C) 2010 Youssef Bakr
 *
 */
package EMAS;

import javax.swing.JFrame;

public class EMASMain extends JFrame {

    //protected BuilderJInternalFrame m_BuilderView = null;
    protected EMAS m_Predictor = null;
        /** The frame containing the explorer interface */
   // protected javax.swing.JInternalFrame m_ExplorerFrame;

    /** Creates new form Main */
    public EMASMain() {
        initComponents();
        setSize(950,670 );
        setTitle("   Epitopes Model Applier Software (EMAS)                                                 https://sites.google.com/site/epitopesprediction");

         m_Predictor = new EMAS();
            theDesktop.add(m_Predictor);
            m_Predictor.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        theDesktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        getContentPane().add(theDesktop, java.awt.BorderLayout.CENTER);
        theDesktop.setBackground(new java.awt.Color(255, 255, 255));
        theDesktop.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EMAS/Flag of Egypt100.gif"))); // NOI18N
        jLabel1.setBounds(430, 300, 100, 100);
        theDesktop.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EMAS/ARC100.jpg"))); // NOI18N
        jLabel2.setBounds(270, 230, 100, 100);
        theDesktop.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EMAS/AGERI100.gif"))); // NOI18N
        jLabel3.setBounds(270, 410, 99, 90);
        theDesktop.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EMAS/Meno100.jpg"))); // NOI18N
        jLabel4.setBounds(570, 230, 120, 100);
        theDesktop.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EMAS/GEBRI 100.jpg"))); // NOI18N
        jLabel5.setBounds(580, 410, 100, 100);
        theDesktop.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EMAS/Egypt100.png"))); // NOI18N
        jLabel6.setBounds(420, 120, 120, 100);
        theDesktop.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EMAS/gplv3.png"))); // NOI18N
        jLabel7.setBounds(410, 500, 140, 70);
        theDesktop.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(theDesktop, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 943, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(theDesktop, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new EMASMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane theDesktop;
    // End of variables declaration//GEN-END:variables
}
