
package epitopespredictionsoftware;

import javax.swing.JFrame;

public class EpsMain extends JFrame {

    //protected BuilderJInternalFrame m_BuilderView = null;
    protected EpitopesPredictionSoftware m_Predictor = null;
        /** The frame containing the explorer interface */
   // protected javax.swing.JInternalFrame m_ExplorerFrame;

    /** Creates new form Main */
    public EpsMain() {
        initComponents();
        setSize(940,480 );
        setTitle("Epitopes Prediction Software (EPS) https://sites.google.com/site/epitopespredictionsoftware/");

         m_Predictor = new EpitopesPredictionSoftware();
            theDesktop.add(m_Predictor);
            m_Predictor.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        theDesktop = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        getContentPane().add(theDesktop, java.awt.BorderLayout.CENTER);
        theDesktop.setBackground(new java.awt.Color(0, 0, 0));
        theDesktop.setForeground(new java.awt.Color(255, 51, 0));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(153, 255, 0));
        jLabel2.setText("For help contact :");
        jLabel2.setBounds(10, 130, 210, 30);
        theDesktop.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setForeground(new java.awt.Color(153, 255, 0));
        jLabel3.setText("https://sites.google.com/site/epitopespredictionsoftware/");
        jLabel3.setBounds(10, 30, 340, 30);
        theDesktop.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setForeground(new java.awt.Color(153, 255, 0));
        jLabel4.setText("This Software is built over previous open source projects EpiT");
        jLabel4.setBounds(10, 60, 350, 30);
        theDesktop.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setForeground(new java.awt.Color(153, 255, 0));
        jLabel5.setText("Epitopes prediction software is open source and released under GPL 3");
        jLabel5.setBounds(10, 10, 470, 30);
        theDesktop.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setForeground(new java.awt.Color(153, 255, 0));
        jLabel6.setText("Email / youssefbakr@gmail.com");
        jLabel6.setBounds(10, 180, 220, 30);
        theDesktop.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setForeground(new java.awt.Color(153, 255, 0));
        jLabel7.setText("Phone No./ +2-01521121000");
        jLabel7.setBounds(10, 210, 210, 30);
        theDesktop.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setForeground(new java.awt.Color(153, 255, 0));
        jLabel8.setText("Youssef Mohamed Bakr Eldoree");
        jLabel8.setBounds(10, 160, 210, 30);
        theDesktop.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setForeground(new java.awt.Color(153, 255, 0));
        jLabel9.setText("Web site     https://sites.google.com/site/youssefbakr/");
        jLabel9.setBounds(10, 240, 370, 30);
        theDesktop.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(theDesktop, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(theDesktop, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new EpsMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane theDesktop;
    // End of variables declaration//GEN-END:variables
}
