package Tim;


/*
 *    This program is free software; you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation; either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with this program; if not, write to the Free Software
 *    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 *
 *
 *    I would like to express my appreciation to two open source project (WEKA and EPIT)
 *    that i used in Tim under the terms of the GNU General Public License.
 *      Copyright (C) 2012 Youssef Bakr
 *
 */


import Tim.Tim;
import javax.swing.JFrame;

public class TimMain extends JFrame {

    //protected BuilderJInternalFrame m_BuilderView = null;
    protected Tim m_Predictor = null;
        /** The frame containing the explorer interface */
   // protected javax.swing.JInternalFrame m_ExplorerFrame;

    /** Creates new form Main */
    public TimMain() {
        initComponents();
        setSize(981,547);
        setTitle("Tool for implementing Models (TiM)                (www.sites.google.com/site/epitopesprediction)         Epitopes Model Applier Software(EMAS)");

         m_Predictor = new Tim();
            theDesktop.add(m_Predictor);
            m_Predictor.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        theDesktop = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMaximizedBounds(theDesktop.getVisibleRect());
        setMinimumSize(new java.awt.Dimension(106, 33));
        setResizable(false);

        getContentPane().add(theDesktop, java.awt.BorderLayout.CENTER);
        theDesktop.setBackground(new java.awt.Color(255, 255, 255));
        theDesktop.setForeground(new java.awt.Color(0, 0, 0));
        theDesktop.setAutoscrolls(true);
        theDesktop.setMinimumSize(new java.awt.Dimension(106, 33));
        theDesktop.setPreferredSize(new java.awt.Dimension(888, 526));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tim/EpiTlogo.JPG"))); // NOI18N
        jLabel2.setBounds(20, 260, 150, 220);
        theDesktop.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tim/Weka_(software)_logo.png"))); // NOI18N
        jLabel1.setBounds(710, 380, 210, 120);
        theDesktop.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tim/TiM_1.jpg"))); // NOI18N
        jLabel4.setBounds(270, 230, 400, 280);
        theDesktop.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tim/gplv3.png"))); // NOI18N
        jLabel5.setBounds(750, 260, 130, 80);
        theDesktop.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Youssef Bakr\nPhD Student \nBioinformatics Department \nAgricultural Genetic Engineering Research Institute (AGERI), \nAgriculture Research Center (ARC), \n9 Gamaa Street,12619 ,Giza, Egypt. \nEmail: youssefbakr@gmail.com \nCell phone: 002 - 011 21 12 1000");
        jScrollPane1.setViewportView(jTextArea1);

        jScrollPane1.setBounds(250, 20, 500, 150);
        theDesktop.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(theDesktop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1005, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(theDesktop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TimMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JDesktopPane theDesktop;
    // End of variables declaration//GEN-END:variables
}
